const axios = require('axios');
const fs = require('fs-extra');
const path = require('path');

module.exports = {
    config: {
        name: "logo",
        version: "2.0.0",
        role: 0,
        author: "Marina Khan",
        category: "design",
        description: "Create beautiful logos with your name",
        guide: "{pn} [your name]"
    },

    onStart: async function({ api, event, args }) {
        try {
            const name = args.join(' ');
            
            if (!name) {
                return api.sendMessage(`🎨 **Logo Designer**\n\nUsage: !logo [Your Name]\nExample: !logo Marina Khan\n\n✨ Create stunning logos instantly!`, event.threadID);
            }

            api.sendMessage(`🔄 Creating logo for "${name}"...`, event.threadID);

            // Use reliable logo APIs
            const logoUrls = [
                `https://api.botcahx.live/api/photooxy/blackpink?text=${encodeURIComponent(name)}&apikey=Admin`,
                `https://api.botcahx.live/api/photooxy/shadow-text?text=${encodeURIComponent(name)}&apikey=Admin`,
                `https://api.botcahx.live/api/photooxy/carved-wood?text=${encodeURIComponent(name)}&apikey=Admin`,
                `https://api.zahwazein.xyz/photooxy/romantic?text=${encodeURIComponent(name)}&apikey=zenzkey_669bcbf0fb`
            ];

            let success = false;
            
            for (let logoUrl of logoUrls) {
                try {
                    const response = await axios.get(logoUrl, { 
                        responseType: 'stream',
                        timeout: 30000 
                    });
                    
                    if (response.status === 200) {
                        await api.sendMessage({
                            body: `✨ **Logo Created Successfully!**\n\n📝 Name: ${name}\n🎨 Style: Professional\n🌈 Generated by Marina AI\n\n💝 Perfect for your brand!`,
                            attachment: response.data
                        }, event.threadID);
                        success = true;
                        break;
                    }
                } catch (apiError) {
                    console.log(`API failed: ${logoUrl}`);
                    continue;
                }
            }

            if (!success) {
                // Fallback to simple text logo
                await createTextLogo(api, event, name);
            }

        } catch (error) {
            console.error("Logo error:", error);
            await createTextLogo(api, event, args.join(' ') || "Your Name");
        }
    }
};

// Fallback text logo
async function createTextLogo(api, event, name) {
    const textLogo = `
╔══════════════════════════╗
║                          ║
║        🎨 LOGO STUDIO    ║
║                          ║
║         ${name}         ║
║                          ║
║    Designed by Marina AI ║
║                          ║
╚══════════════════════════╝
    `;
    
    api.sendMessage(`✨ **Text Logo Created**\n\n${textLogo}\n\n💡 Tip: The image logo service is temporarily unavailable.`, event.threadID);
}
