const fs = require('fs-extra');
const path = require('path');

const commentsDatabase = path.join(__dirname, '..', 'data', 'fb_comments.json');

module.exports = {
    config: {
        name: "fcomment",
        version: "1.0",
        author: "Marina",
        countDown: 5,
        role: 1,
        description: {
            en: "Generate Facebook post comments for different types of posts"
        },
        category: "comments",
        guide: {
            en: "{p}fcomment [type] [count]\n{p}fcomment add [type] [comment]\n{p}fcomment types"
        }
    },

    onStart: async function ({ api, event, args }) {
        await this.ensureDataDir();
        
        const action = args[0];
        
        if (!action) {
            const helpMessage = `💬 **FACEBOOK POST COMMENT GENERATOR** 💬

👑 **Powered by Marina - Comment Expert**

🎯 **Comment Types:**
• islamic - Islamic posts & greetings
• funny - Funny & humorous posts
• love - Love & relationship posts
• sad - Emotional & sad posts
• angry - Controversial posts
• wow - Amazing content
• support - Supportive comments
• question - Question posts
• news - News posts
• photo - Photo posts
• video - Video posts
• status - Status updates
• marina - Marina special comments

💡 **Usage Examples:**
{p}fcomment islamic 10
{p}fcomment funny 5
{p}fcomment love 3
{p}fcomment add islamic "Masha Allah beautiful post!"
{p}fcomment types

🌟 **Perfect for engaging with any Facebook post!**`;

            await api.sendMessage(helpMessage, event.threadID);
            return;
        }

        if (action === 'add') {
            await this.handleAddComment(api, event, args.slice(1));
        } else if (action === 'types') {
            await this.showCommentTypes(api, event);
        } else {
            await this.generateFBComments(api, event, args);
        }
    },

    generateFBComments: async function (api, event, args) {
        const type = args[0] || 'islamic';
        const count = parseInt(args[1]) || 5;
        
        if (count > 20) {
            return api.sendMessage("❌ Maximum 20 comments at a time for better performance.", event.threadID);
        }

        const comments = await this.getFBComments(type, count);
        if (comments.length === 0) {
            return api.sendMessage(`❌ No comments found for type: ${type}`, event.threadID);
        }

        let response = `💬 **FACEBOOK ${type.toUpperCase()} COMMENTS** 💬\n\n`;
        comments.forEach((comment, index) => {
            response += `${index + 1}. ${comment}\n\n`;
        });

        response += `\n👑 Generated by Marina's Comment System\n📊 ${comments.length} comments ready for Facebook!`;

        await api.sendMessage(response, event.threadID);
    },

    handleAddComment: async function (api, event, args) {
        const type = args[0];
        const text = args.slice(1).join(' ');
        
        if (!type || !text) {
            return api.sendMessage("❌ Use: fcomment add [type] [comment text]", event.threadID);
        }

        try {
            const commentsData = await fs.readJson(commentsDatabase);
            if (!commentsData[type]) {
                commentsData[type] = [];
            }
            
            commentsData[type].push(text);
            await fs.writeJson(commentsDatabase, commentsData);
            
            await api.sendMessage(`✅ Added new ${type} comment to Facebook database! 💾`, event.threadID);
        } catch (error) {
            await api.sendMessage("❌ Error adding comment to database.", event.threadID);
        }
    },

    showCommentTypes: async function (api, event) {
        const typesInfo = `📋 **FACEBOOK COMMENT TYPES** 📋

🕌 ISLAMIC - For Islamic posts, Quran verses, mosque photos
😂 FUNNY - For memes, jokes, humorous content
❤️ LOVE - For relationship posts, love stories
😢 SAD - For emotional posts, sad news
😠 ANGRY - For controversial topics, debates
😮 WOW - For amazing achievements, surprises
💪 SUPPORT - For motivational posts, achievements
❓ QUESTION - For question posts, polls
📰 NEWS - For news articles, updates
📸 PHOTO - For photo posts, selfies
🎥 VIDEO - For video posts, reels
📝 STATUS - For status updates, thoughts
👑 MARINA - Special Marina branded comments

💫 Each type has 50+ unique comments!`;
        
        await api.sendMessage(typesInfo, event.threadID);
    },

    getFBComments: async function (type, count) {
        try {
            const commentsData = await fs.readJson(commentsDatabase);
            const typeComments = commentsData[type] || this.getDefaultFBComments(type);
            
            const shuffled = [...typeComments].sort(() => 0.5 - Math.random());
            return shuffled.slice(0, Math.min(count, shuffled.length));
        } catch (error) {
            return this.getDefaultFBComments(type).slice(0, count);
        }
    },

    getDefaultFBComments: function (type) {
        const defaultComments = {
            islamic: [
                "Masha Allah! 🌟 Beautiful Islamic post.",
                "Subhanallah! May Allah bless you. 🤲",
                "JazakAllah Khair for sharing this! 💫",
                "Allahu Akbar! Wonderful reminder. 🕌",
                "Masha Allah tabarakallah! ✨",
                "Beautiful Quranic verse! 📖",
                "May Allah accept our deeds. Ameen 🤲",
                "Islamic knowledge is the best knowledge! 🎯",
                "Subhanallah, so meaningful! 💖",
                "Allah is the Greatest! ⚡",
                "Perfect timing for this reminder! ⏰",
                "Masha Allah, heart touching! ❤️",
                "JazakAllah for this beneficial post! 🌸",
                "Allah bless the one who shared this! 🙏",
                "Subhanallah, so true! 💯"
            ],

            funny: [
                "Hahaha! This made my day! 😂",
                "LOL! Too funny! 🤣",
                "You got me laughing out loud! 😄",
                "This is pure gold! 🤣",
                "Hahaha brilliant! 😝",
                "Can't stop laughing! 😂",
                "You're hilarious! 🤪",
                "This deserves to go viral! 🚀",
                "Hahaha amazing sense of humor! 😆",
                "ROFL! 🤣",
                "This is comedy gold! 🎭",
                "You should be a comedian! 😄",
                "Hahaha too good! 🤣",
                "My stomach hurts from laughing! 😂",
                "This made me spit my drink! 💦"
            ],

            love: [
                "So much love! ❤️ Beautiful post.",
                "This is so heartwarming! 💕",
                "True love exists! 💖",
                "Relationship goals! 👫",
                "So sweet and caring! 💘",
                "This made me smile! 😊",
                "Love is beautiful! 💝",
                "You two are amazing together! 💑",
                "This is true love! 💗",
                "So romantic! 💓",
                "Love wins always! 💞",
                "Beautiful love story! 💟",
                "This is so pure! ❣️",
                "Love conquers all! 💌",
                "You deserve all the love! 💖"
            ],

            sad: [
                "This is so sad 😢 Sending prayers.",
                "Heartbreaking 💔 Stay strong!",
                "This brought tears to my eyes 😭",
                "So emotional and touching 😔",
                "My heart goes out to you 🤲",
                "This is really sad 😞",
                "Sending love and support 💝",
                "Can feel the emotion 😥",
                "This is heartbreaking 😿",
                "Stay strong, better days ahead 💫",
                "This made me emotional 😰",
                "Sending virtual hugs 🫂",
                "Tears in my eyes 😓",
                "This is so moving 😩",
                "Praying for better times 🌈"
            ],

            angry: [
                "This is so wrong! 😠",
                "How can people do this? 😡",
                "This makes me angry! 🤬",
                "Unacceptable behavior! 👿",
                "This is ridiculous! 💢",
                "How dare they do this! 👺",
                "This is infuriating! 😤",
                "Completely unacceptable! 🤯",
                "This is terrible! 😾",
                "So frustrating to see this! 💀",
                "This needs to stop! 🛑",
                "How can this happen? 😠",
                "This is outrageous! 😡",
                "Someone should do something! ⚖️",
                "This is not right! ❌"
            ],

            wow: [
                "Wow! This is amazing! 😮",
                "Incredible achievement! 🤩",
                "Absolutely fantastic! 🎉",
                "Brilliant work! ✨",
                "Outstanding! 🌟",
                "Magnificent! 👑",
                "Spectacular! 💫",
                "Phenomenal! 🔥",
                "Extraordinary! 🚀",
                "Mind-blowing! 🤯",
                "Absolutely stunning! 💎",
                "This is epic! 🏆",
                "Beyond amazing! 🌈",
                "Simply wonderful! 👍",
                "This is next level! ⭐"
            ],

            support: [
                "You can do it! 💪 Keep going!",
                "I believe in you! 🌟",
                "You're amazing! ✨",
                "Stay strong! 💖",
                "We support you! 👏",
                "You got this! 🔥",
                "Proud of you! 🎯",
                "Keep shining! ☀️",
                "You're doing great! 👍",
                "Don't give up! 🚀",
                "You're stronger than you think! 💎",
                "Keep moving forward! 🔄",
                "You're capable of anything! 🌈",
                "Stay positive! 😊",
                "You're a warrior! ⚔️"
            ],

            photo: [
                "Great photo! 📸 Looking amazing!",
                "Wonderful picture! 🖼️",
                "Photo perfect! 👍",
                "Beautiful capture! 🌟",
                "Awesome shot! 🎯",
                "Picture perfect moment! 📷",
                "Lovely photo! 💝",
                "Amazing picture quality! 🔥",
                "Stunning photo! ✨",
                "Perfect click! ✅",
                "Beautiful memories! 💫",
                "Great photography! 👌",
                "Lovely capture! 🎨",
                "Photo of the day! 🏆",
                "Fantastic picture! 🚀"
            ],

            video: [
                "Great video! 🎥 Loved it!",
                "Awesome video content! 🔥",
                "Video is amazing! ✨",
                "Well made video! 👍",
                "Enjoyed watching! 🎬",
                "Fantastic video! 🚀",
                "Video is fire! 🔥",
                "Loved the video! ❤️",
                "Great content! 📹",
                "Video is perfect! ✅",
                "Amazing video quality! 💎",
                "Well edited video! 🎭",
                "Video is brilliant! 🌟",
                "Loved every second! ⏱️",
                "Perfect video! 🏆"
            ],

            marina: [
                "Marina approves this post! 👑",
                "From Marina with love! 💝",
                "Marina's seal of approval! ✅",
                "Powered by Marina's wisdom! 💻",
                "Marina says this is great! 🌟",
                "Marina's favorite type of post! 🎯",
                "Marina would love this! 💫",
                "Marina's comment: Awesome! 🔥",
                "Marina's tech insight: Perfect! 💎",
                "Marina sends love for this post! ❤️",
                "Marina's developer perspective: Great! 🚀",
                "Marina finds this post amazing! ✨",
                "Marina's expert opinion: Wonderful! 👍",
                "Marina's special comment: Brilliant! 🌈",
                "Marina's final verdict: Excellent! 🏆"
            ]
        };

        return defaultComments[type] || ["Great post! 👍"];
    },

    ensureDataDir: async function () {
        const dataDir = path.join(__dirname, '..', 'data');
        await fs.ensureDir(dataDir);
        if (!fs.existsSync(commentsDatabase)) {
            await fs.writeJson(commentsDatabase, {});
        }
    }
};
